# Generated by Django 2.0.1 on 2018-01-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('vault', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('opened', models.BooleanField(default=True)),
            ],
        ),
    ]
