# Generated by Django 2.0.1 on 2018-01-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
