# Generated by Django 2.0.1 on 2018-01-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
